spring.application.name=student-management-system
server.port = 1314

spring.datasource.url = jdbc:postgresql://localhost:5432/studentmanagementDB
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = Vinnu*7376

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true